[package]
name = "clmm_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4.18", features = ["derive", "cargo"] }
solana-sdk = "1.18.1"
solana-client = "1.18.1"
anchor-lang = "0.29.0"
